spring.application.name=kundtjänsten



# --- MySQL ---
spring.datasource.url=jdbc:mysql://mysql.railway.internal:3306/kundtjansten
spring.datasource.username=root
spring.datasource.password=CzrLFYHztSEbzDxtDuavGBAXMbxQJUKD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Server ---
server.port=8081

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
